### ISSUE TITLE
Add redotjs to unified website!

### ISSUE THREAD

**Issue by wooorm** [redotjs/ideas#5]
When redot is ready, we should add it to the unified website, unified readme, @syntax-tree org, etc!

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @wooorm  !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/redotjs/redot/discussions/categories/ideas will be the home for ideas going forward.
